import { ActivityDefinitionSchema } from "@/core/activity";

export const alpinefitBrainstormingV3 = ActivityDefinitionSchema.parse({
  id: "alpinefit-brainstorming-v3",
  contentVersion: 1,
  eventSchemaVersion: 3,
  scoringVersion: "v3",
  status: "active",
  title: "Build a focused set of AlpineFit profit drivers",
  labId: "brainstorming",
  primarySkillId: "brainstorming",
  secondarySkillIds: ["prioritization"],
  difficulty: "beginner",
  estimatedMinutes: 7,
  caseTypeIds: ["profitability"],
  industryIds: ["fitness"],
  interaction: {
    type: "brainstorm_builder",
    interactionId: "alpinefit-profit-drivers",
    prompt: "Select distinct drivers, organize them, then prioritize the strongest lead.",
    categories: [
      { id: "revenue", label: "Revenue" },
      { id: "labor", label: "Labor and staffing" },
      { id: "other-costs", label: "Other operating costs" },
    ],
    ideas: [
      { id: "revenue-price", label: "Membership price or discount mix", categoryIds: ["revenue"], relevant: true, redundantWithIds: ["revenue-price-duplicate"] },
      { id: "revenue-price-duplicate", label: "Average price paid by members", categoryIds: ["revenue"], relevant: true, redundantWithIds: ["revenue-price"] },
      { id: "revenue-volume", label: "Member volume and retention", categoryIds: ["revenue"], relevant: true, redundantWithIds: [] },
      { id: "labor-overtime", label: "Overtime hours and premium", categoryIds: ["labor"], relevant: true, redundantWithIds: [] },
      { id: "labor-vacancies", label: "Vacancies and staff turnover", categoryIds: ["labor"], relevant: true, redundantWithIds: [] },
      { id: "other-occupancy", label: "Occupancy expense", categoryIds: ["other-costs"], relevant: true, redundantWithIds: [] },
      { id: "other-logo", label: "Logo color", categoryIds: ["other-costs"], relevant: false, redundantWithIds: [] },
    ],
    minimumCategoryCoverage: 3,
    maximumPriorityIdeas: 2,
    outcomeIds: ["strong", "reasonable", "narrow", "weak"],
  },
  feedback: { paths: [
    {
      id: "strong",
      classification: "strong",
      diagnosticCodes: ["strong_brainstorm"],
      explanation: "Your set covers distinct revenue and cost drivers and identifies a lead to test.",
      principle: "Breadth comes from distinct categories, not a long list.",
      nextAction: "Test the prioritized driver with the most decision-relevant evidence.",
    },
    {
      id: "reasonable",
      classification: "reasonable",
      diagnosticCodes: ["brainstorm_breadth_narrow"],
      explanation: "The ideas are relevant and distinct, but one major driver category is missing.",
      principle: "Check category coverage before adding detail within one bucket.",
      nextAction: "Add one distinct driver from the missing category.",
    },
    {
      id: "narrow",
      classification: "weak",
      diagnosticCodes: ["brainstorm_breadth_narrow"],
      explanation: "The set stays inside one driver category and misses major alternatives.",
      principle: "Check category coverage before adding more ideas within one bucket.",
      nextAction: "Add distinct revenue and cost drivers before prioritizing.",
    },
    {
      id: "weak",
      classification: "weak",
      diagnosticCodes: ["brainstorm_categories_overlap", "brainstorm_off_objective"],
      explanation: "The set includes overlap or an idea that does not address the margin decision.",
      principle: "Remove duplicates and off-objective ideas before prioritizing.",
      nextAction: "Keep one version of each driver and cover the major profit buckets.",
    },
  ] },
  takeaway: "Organize for coverage, remove overlap, then prioritize.",
});
