export const diagnosticCodes = [
  "objective_not_reframed",
  "material_term_unresolved",
  "constraint_missed",
  "low_value_question",
  "question_overload",
  "strong_opening",
  "missing_major_branch",
  "overlapping_branches",
  "branch_too_vague",
  "branch_not_testable",
  "priority_missing",
  "strong_structure",
  "low_information_value",
  "premature_detail",
  "hypothesis_not_linked",
  "failed_to_update",
  "immaterial_branch_continued",
  "strong_priority",
  "setup_error",
  "arithmetic_error",
  "unit_error",
  "sense_check_missing",
  "business_implication_missing",
  "strong_quantitative_reasoning",
  "observation_error",
  "comparison_missed",
  "implication_missing",
  "next_test_missing",
  "strong_exhibit_chain",
  "answer_not_first",
  "evidence_dump",
  "evidence_unsupported",
  "next_step_missing",
  "strong_synthesis",
  "recommendation_not_answer_first",
  "support_insufficient",
  "risk_missing",
  "strong_recommendation",
  "hypothesis_missing",
  "evidence_link_missing",
  "update_missing",
  "contradicted_hypothesis_retained",
  "strong_hypothesis_update",
] as const;

export type DiagnosticCode = (typeof diagnosticCodes)[number];

export const diagnosticAreas = [
  "clarification",
  "structure",
  "prioritization",
  "quantitative",
  "exhibit",
  "synthesis",
  "recommendation",
  "hypothesis",
] as const;

export type DiagnosticArea = (typeof diagnosticAreas)[number];

const areaByCode: Record<DiagnosticCode, DiagnosticArea> = {
  objective_not_reframed: "clarification",
  material_term_unresolved: "clarification",
  constraint_missed: "clarification",
  low_value_question: "clarification",
  question_overload: "clarification",
  strong_opening: "clarification",
  missing_major_branch: "structure",
  overlapping_branches: "structure",
  branch_too_vague: "structure",
  branch_not_testable: "structure",
  priority_missing: "structure",
  strong_structure: "structure",
  low_information_value: "prioritization",
  premature_detail: "prioritization",
  hypothesis_not_linked: "prioritization",
  failed_to_update: "prioritization",
  immaterial_branch_continued: "prioritization",
  strong_priority: "prioritization",
  setup_error: "quantitative",
  arithmetic_error: "quantitative",
  unit_error: "quantitative",
  sense_check_missing: "quantitative",
  business_implication_missing: "quantitative",
  strong_quantitative_reasoning: "quantitative",
  observation_error: "exhibit",
  comparison_missed: "exhibit",
  implication_missing: "exhibit",
  next_test_missing: "exhibit",
  strong_exhibit_chain: "exhibit",
  answer_not_first: "synthesis",
  evidence_dump: "synthesis",
  evidence_unsupported: "synthesis",
  next_step_missing: "synthesis",
  strong_synthesis: "synthesis",
  recommendation_not_answer_first: "recommendation",
  support_insufficient: "recommendation",
  risk_missing: "recommendation",
  strong_recommendation: "recommendation",
  hypothesis_missing: "hypothesis",
  evidence_link_missing: "hypothesis",
  update_missing: "hypothesis",
  contradicted_hypothesis_retained: "hypothesis",
  strong_hypothesis_update: "hypothesis",
};

export type DiagnosticDefinition = {
  code: DiagnosticCode;
  area: DiagnosticArea;
  explanation: string;
  recommendedNextRep: string;
};

const learnerCopy: Record<DiagnosticCode, string> = {
  objective_not_reframed: "Restate the decision you are trying to make.",
  material_term_unresolved: "Clarify the metric, timing, or scope before analyzing.",
  constraint_missed: "Include the constraint that shapes the decision.",
  low_value_question: "Choose a question that could change the analysis.",
  question_overload: "Ask fewer, higher-value opening questions.",
  strong_opening: "You framed the decision and resolved useful ambiguity.",
  missing_major_branch: "Add the major branch missing from the structure.",
  overlapping_branches: "Make the branches distinct so evidence has one clear home.",
  branch_too_vague: "Make each branch specific enough to investigate.",
  branch_not_testable: "Turn the branch into something evidence can confirm or reject.",
  priority_missing: "Choose the first branch and explain why it matters most.",
  strong_structure: "Your structure is distinct, testable, and prioritized.",
  low_information_value: "Choose a next step that distinguishes between explanations.",
  premature_detail: "Resolve the main uncertainty before pursuing detail.",
  hypothesis_not_linked: "Connect the hypothesis to evidence that could test it.",
  failed_to_update: "Explain how the new evidence changes the working hypothesis.",
  immaterial_branch_continued: "Move away from a branch after evidence makes it immaterial.",
  strong_priority: "You chose the next step with the highest decision value.",
  setup_error: "Rebuild the equation from the business relationships.",
  arithmetic_error: "Check the arithmetic after confirming the setup.",
  unit_error: "State the correct unit with your answer.",
  sense_check_missing: "Check whether the result is plausible in context.",
  business_implication_missing: "Explain what the number means for the decision.",
  strong_quantitative_reasoning: "Your setup, result, unit, and implication are connected.",
  observation_error: "Start with a factual observation supported by the exhibit.",
  comparison_missed: "Use the comparison that best distinguishes the result.",
  implication_missing: "Explain what the exhibit means for the case.",
  next_test_missing: "Turn the implication into a focused next analysis.",
  strong_exhibit_chain: "You connected observation, implication, and next action.",
  answer_not_first: "Lead the synthesis with the current answer.",
  evidence_dump: "Use only the evidence that supports the conclusion.",
  evidence_unsupported: "Connect each claim to evidence revealed in the case.",
  next_step_missing: "Close with the uncertainty or analysis that comes next.",
  strong_synthesis: "Your synthesis leads with an answer and uses decisive evidence.",
  recommendation_not_answer_first: "Start with a clear recommendation.",
  support_insufficient: "Support the recommendation with the strongest case evidence.",
  risk_missing: "Name a material risk and a practical next step.",
  strong_recommendation: "Your recommendation is clear, supported, and actionable.",
  hypothesis_missing: "State a testable explanation before investigating.",
  evidence_link_missing: "Name the evidence used to retain, revise, or reject the claim.",
  update_missing: "Decide whether the evidence supports changing the hypothesis.",
  contradicted_hypothesis_retained: "Revise a hypothesis when the evidence contradicts it.",
  strong_hypothesis_update: "You updated the claim using specific evidence.",
};

export const diagnosticDefinitions = Object.fromEntries(
  diagnosticCodes.map((code) => [
    code,
    {
      code,
      area: areaByCode[code],
      explanation: learnerCopy[code],
      recommendedNextRep: areaByCode[code],
    } satisfies DiagnosticDefinition,
  ]),
) as Record<DiagnosticCode, DiagnosticDefinition>;
